[package]
name = 'jsdotlua/more-polyfill'
description = 'https://github.com/grilme99/CorePackages'
version = '0.1.0'
license = 'MIT'
authors = ['jsdotlua']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
